"""create recommendation logs

Revision ID: c706f52f6008
Revises: ae1bd4623b24
Create Date: 2026-09-26 19:50:55.330273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c706f52f6008'
down_revision: Union[str, Sequence[str], None] = 'ae1bd4623b24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('scoring_version', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], name=op.f('fk_recommendation_logs_apartment_id_apartments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recommendation_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_logs'))
    )
    op.create_index(op.f('ix_recommendation_logs_apartment_id'), 'recommendation_logs', ['apartment_id'], unique=False)
    op.create_index(op.f('ix_recommendation_logs_request_id'), 'recommendation_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_recommendation_logs_user_id'), 'recommendation_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_logs_user_id'), table_name='recommendation_logs')
    op.drop_index(op.f('ix_recommendation_logs_request_id'), table_name='recommendation_logs')
    op.drop_index(op.f('ix_recommendation_logs_apartment_id'), table_name='recommendation_logs')
    op.drop_table('recommendation_logs')
    # ### end Alembic commands ###
