"""initial schema

Revision ID: f93b227bd449
Revises:
Create Date: 2026-09-26 17:27:31.592472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f93b227bd449'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('source_id', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('center_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('center_longtitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('geometry', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_districts')),
    sa.UniqueConstraint('source', 'source_id', name='uq_districts_source_source_id')
    )
    op.create_index(op.f('ix_districts_name'), 'districts', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role'), server_default='user', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.create_table('apartments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='RUB', nullable=False),
    sa.Column('deal_type', sa.Enum('sale', 'rent', name='apartment_deal_type'), nullable=False),
    sa.Column('rent_period', sa.Enum('day', 'month', name='rent_period'), nullable=True),
    sa.Column('area', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('total_floors', sa.Integer(), nullable=False),
    sa.Column('building_year', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('house_number', sa.String(length=32), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('coordinate_method', sa.String(length=64), nullable=True),
    sa.Column('district_assignment_method', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('complex_source_id', sa.String(length=128), nullable=True),
    sa.Column('complex_name', sa.String(length=255), nullable=True),
    sa.Column('complex_source_url', sa.String(length=1024), nullable=True),
    sa.Column('market_type', sa.String(length=64), nullable=True),
    sa.Column('offer_type', sa.String(length=64), nullable=True),
    sa.Column('origin', sa.Enum('seed', 'user', name='apartment_origin'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_sha256', sa.String(length=64), nullable=True),
    sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'hidden', 'deleted', name='apartment_status'), server_default='published', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name=op.f('fk_apartments_district_id_districts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_apartments_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_apartments')),
    sa.UniqueConstraint('dataset_id', name=op.f('uq_apartments_dataset_id')),
    sa.UniqueConstraint('source', 'source_id', name='uq_apartments_source_source_id')
    )
    op.create_index(op.f('ix_apartments_deal_type'), 'apartments', ['deal_type'], unique=False)
    op.create_index(op.f('ix_apartments_district_id'), 'apartments', ['district_id'], unique=False)
    op.create_index(op.f('ix_apartments_owner_id'), 'apartments', ['owner_id'], unique=False)
    op.create_index(op.f('ix_apartments_source'), 'apartments', ['source'], unique=False)
    op.create_index(op.f('ix_apartments_status'), 'apartments', ['status'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions'))
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('apartment_features',
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'ready', 'failed', name='apartment_feature_status'), server_default='pending', nullable=False),
    sa.Column('schools_1km', sa.Integer(), nullable=True),
    sa.Column('kindergartens_1km', sa.Integer(), nullable=True),
    sa.Column('parks_1km', sa.Integer(), nullable=True),
    sa.Column('shops_1km', sa.Integer(), nullable=True),
    sa.Column('transport_stops_1km', sa.Integer(), nullable=True),
    sa.Column('nearest_school_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('nearest_kindergarten_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('nearest_park_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('nearest_transport_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('feature_version', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], name=op.f('fk_apartment_features_apartment_id_apartments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('apartment_id', name=op.f('pk_apartment_features'))
    )
    op.create_index(op.f('ix_apartment_features_status'), 'apartment_features', ['status'], unique=False)
    op.create_table('apartment_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('bucket', sa.String(length=128), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('local_path', sa.String(length=1024), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('listing_url', sa.String(length=2048), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_cover', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('original_sha256', sa.String(length=64), nullable=True),
    sa.Column('rights_status', sa.String(length=128), nullable=True),
    sa.Column('attribution', sa.String(length=1024), nullable=True),
    sa.Column('publication_allowed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('image_kind', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], name=op.f('fk_apartment_photos_apartment_id_apartments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_apartment_photos')),
    sa.UniqueConstraint('apartment_id', 'position', name='uq_apartment_photos_apartment_position'),
    sa.UniqueConstraint('bucket', 'storage_key', name='uq_apartment_photos_bucket_storage_key'),
    sa.UniqueConstraint('external_id', name=op.f('uq_apartment_photos_external_id'))
    )
    op.create_index(op.f('ix_apartment_photos_apartment_id'), 'apartment_photos', ['apartment_id'], unique=False)
    op.create_index('uq_apartment_photos_cover_per_apartment', 'apartment_photos', ['apartment_id'], unique=True, postgresql_where=sa.text('is_cover = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_apartment_photos_cover_per_apartment', table_name='apartment_photos', postgresql_where=sa.text('is_cover = true'))
    op.drop_index(op.f('ix_apartment_photos_apartment_id'), table_name='apartment_photos')
    op.drop_table('apartment_photos')
    op.drop_index(op.f('ix_apartment_features_status'), table_name='apartment_features')
    op.drop_table('apartment_features')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_apartments_status'), table_name='apartments')
    op.drop_index(op.f('ix_apartments_source'), table_name='apartments')
    op.drop_index(op.f('ix_apartments_owner_id'), table_name='apartments')
    op.drop_index(op.f('ix_apartments_district_id'), table_name='apartments')
    op.drop_index(op.f('ix_apartments_deal_type'), table_name='apartments')
    op.drop_table('apartments')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_districts_name'), table_name='districts')
    op.drop_table('districts')
    # ### end Alembic commands ###
